# Generated by Django 4.0 on 2021-12-26 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
